### ISSUE TITLE
Input Data Validations

### ISSUE THREAD

**Issue by HemantKMehta** [JanssenProject/jans-cli#10]
To minimize the  runtime errors : 
1. It will nice if we add validation on data type and correct/ valid values (for example the given value of some field like default authentication method is a valid authentication method) and 
2. During update if the input inum  is not found then swagger_client.rest.ApiException will be raised. Can we display given inum is not found please input correct inum ?

**Comment by mbaser** [comment]
1) cli validates data types according to yaml, and force to input if the variable is marked as **required** in yaml.
2) With this commit https://github.com/JanssenProject/jans-cli/commit/72f43814a25e47887fc8a6035e2a2c153563d5a9 CLI handles api exceptions.
![Screenshot_2021-01-26_20-50-57](https://user-images.githubusercontent.com/6398752/105883862-6383dd80-6018-11eb-986f-a60d377f8166.png)

**Comment by HemantKMehta** [comment]
Please see attached image when I tried it doesn't stop for selection instead directly goes for option 1 get list of gluu attributes from attribute submenu. 
![Screenshot from 2021-01-27 17-59-19](https://user-images.githubusercontent.com/70174684/105991304-9e921980-60c9-11eb-8e53-d4670d35280c.png)
