### ISSUE TITLE
AttributeError: 'SectorIdentifier' object has no attribute 'inum'

### ISSUE THREAD

**Issue by imShakil** [JanssenProject/jans-cli#19]
I tried to update a sector identifier but failed. It ask to enter `inum` value. If I enter the `inum` value, It shows **AttributeError: 'SectorIdentifier' object has no attribute 'inum'** . Please see the attached image.

![Screenshot from 2021-03-24 03-42-38](https://user-images.githubusercontent.com/20867846/112222620-fd4fbb80-8c52-11eb-93e7-a73a974c818c.png)

**Comment by mbaser** [comment]
Fixed by commit

![Screenshot_2021-03-27_21-38-26](https://user-images.githubusercontent.com/6398752/112730835-d3ddab00-8f44-11eb-9d58-c979822f6522.png)

**Comment by nynymike** [comment]
This feature was dropped!  To evaluate a sector identifier, you must strip everything after the hostname (i.e. it ignores the path).
So all sector identifiers generated by gluu would essentially collide. You can register a sector_identifier for a client, we just don’t publish them in the Gluu Server anymore. See [OpenID Connect Core 8.1](https://openid.net/specs/openid-connect-core-1_0.html#PairwiseAlg)
