### ISSUE TITLE
User Management via SCIM

### ISSUE THREAD

**Issue by nynymike** [JanssenProject/jans-cli#3]
It would be a nice feature to add user management to the CLI. For example, add / edit / delete a user. Also, view / delete FIDO devices for a person.

**Comment by mbaser** [comment]
@nynymike please create such issues on jans-config-api. cli just uses swagger.yaml so if it has no such feature, cli has nothing to do

**Comment by nynymike** [comment]
I don't see it as a hard and fast rule that the config-api can't use the SCIM API also. BTW, SCIM has it's own swagger yaml file. Alternately, we could perhaps use a different cli command. But I think it should also go in this repo.

**Comment by mbaser** [comment]
jans-cli works with scim swagger ui with small changes (both cli and yam file)

![scim](https://user-images.githubusercontent.com/6398752/103657667-3a24e400-4f7b-11eb-917b-ed856da2798c.gif)
