### ISSUE TITLE
Unable to set Client responseType to "code id_token" - Hybrid Flow

### ISSUE THREAD

**Issue by ruiengana** [JanssenProject/jans-cli#4]
Hi!

We are getting an error when setting a client responseTypes to "code id_token", I am assuming this is being check by CLI rather than API. See below logs.

```
«A list of the OAuth 2.0 response_type values that the Client is declaring that it will restrict itself to using. If omitted, the default is that the Client will use only the code Response Type. Allowed values are code, token, id_token. Type: array of string seperated by _, Valid values: code, token, id_token»
responseTypes [['code', 'id_token']]: code id_token
Please enter array of code, token, id_token seperated by _,
responseTypes [['code', 'id_token']]:
```
NOTE: There is a typo in "seperated" word, correct form is "separated" :)

**Comment by mbaser** [comment]
You need to type `code_,id_token`
In jca-cli, I used underscore (`_`) as an escape character

**Comment by ruiengana** [comment]
> You need to type `code_,id_token`
> In jca-cli, I used underscore (`_`) as an escape character

We tried that but result is not correct. We get ['code', 'id_token'] and what we want is ['code id_token']

**Comment by mbaser** [comment]
`code id_token` is not a valid entry. According to yaml file (https://github.com/JanssenProject/jans-config-api/blob/master/docs/jans-config-api-swagger.yaml#L3716-L3724) response types can be array of this enum:

```
            enum:
              - code
              - token
              - id_token 
```

**Comment by mbaser** [comment]
@pujavs  When I remove `enum` from yaml file, and post to server this one:
```
  "responseTypes": [
    "token",
    "code id_token"
  ]
```
Server responds:
```
  "responseTypes": [
    "token",
    null
  ]
```

**Comment by pujavs** [comment]
Don’t see any issue with jans-config-api code.  
"responseTypes" is a array of string 
So if you want to specify valid response for client as code as well as id_token then you have to specify two strings in the array that ['code','id_token']
I have tested the same in plain client script by giving response_types=[‘code’,’id_token’] it works and persists the values correctly as code and id_token.
Hope this clarifies.

![image](https://user-images.githubusercontent.com/43700552/103766787-702e9a80-5045-11eb-8cdf-31842121c1d2.png)

**Comment by mbaser** [comment]
Closing this issue, since only `["code", "id_token"]` is supported. No support for `["code", "id_token"]`. 
See supported response types:https://github.com/JanssenProject/jans-setup/blob/master/templates/jans-auth/jans-auth-config.json#L28
