### ISSUE TITLE
Automatically generate inum value 

### ISSUE THREAD

**Issue by HemantKMehta** [JanssenProject/jans-cli#9]
Instead of asking the user to input inum value during add a configuration setting (like adding attribute, adding custom script... etc.)  it will be better if jans-cli automatically generate the inum. This will reduce the chance of runtime error at the end due to duplicate/ wrong value.

**Comment by mbaser** [comment]
We don't need to enter inum, config-api (or oxauth) creates it automatically. With  commit
https://github.com/JanssenProject/jans-cli/commit/84fa0e32880e408887ff5c85a0659edd9ce2a2e6
cli won't as inum and dn
